app/catalog/models.py
from app import db

import datetime


class Publication(db.Model):
	__tablename__ = 'publication'

	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(80),nullable = False)

	def __init__(self,name):
		self.name = name

	def __repr__(self):
		return 'id is {} and name is {}'.format(self.id,self.name)

class Book(db.Model):
	__tablename__ = 'book'

	id = db.Column(db.Integer,primary_key = True)
	title = db.Column(db.String(80),nullable = False, index = True)
	author = db.Column(db.String(80))
	avg_rating = db.Column(db.Float)
	format = db.Column(db.String(80))
	image = db.Column(db.String(80),unique = True)
	num_pages = db.Column(db.Integer)
	pub_date = db.Column(db.DateTime,default=datetime.datetime.utcnow())

	#foreign key
	pub_id = db.Column(db.Integer,db.ForeignKey('publication.id'))


	def __init__(self,title,author,avg_rating,format,image,num_pages,pub_id):
		self.title = title
		self.author = author
		self.avg_rating = avg_rating
		self.format = format
		self.image = image
		self.num_pages = num_pages
		self.pub_id = pub_id

	def __repr__(self):
		return 'title: {} and author : {}'.format(self.title,self.author)

app/catalog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField,BooleanField
from wtforms.validators import DataRequired, Email, Length,ValidationError,EqualTo

class EditForm(FlaskForm):

	title = StringField('Enter the book Title',validators=[DataRequired()])
	format = StringField('Enter the book Format',validators=[DataRequired()])
	num_pages = StringField('Enter the book Pages',validators=[DataRequired()])
	submit = SubmitField('Submit')

class BookForm(FlaskForm):

	title = StringField('Enter the Title',validators=[DataRequired(),Length(5,message="title should be of minimum length 3")])
	author = StringField('Enter the Author',validators=[DataRequired(),Length(5,message="Author should be of minimum length 3")])
	avg_rating = StringField('Enter the Average rating',validators=[DataRequired()])
	format = StringField('Enter the Format',validators=[DataRequired()])
	image = StringField('Enter the Image path',validators=[DataRequired()])
	num_pages = StringField('Enter the Number of pages',validators=[DataRequired()])
	publication = StringField('Enter the publication id',validators=[DataRequired()])
	submit = SubmitField('Submit')

app/catalog/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__,template_folder='templates')

from app.catalog import routes

app/catalog/routes.py
from app.catalog import main
from app.catalog.models import Book, Publication
from flask import render_template,request,redirect,url_for,flash
from app import db
from flask_login import login_required
from app.catalog.forms import EditForm,BookForm

@main.route('/')
@main.route('/books')
def book_details():
	books = Book.query.all()
	publications=[]
	for book in books:
		publication = Publication.query.filter_by(id=book.pub_id).first()
		book.pub_name = publication.name
		publications.append(publication.name)
	return render_template('home.html',books = books,publications = publications)

@main.route('/display/publisher/<publisher_id>')
def display_publisher(publisher_id):
	publisher = Publication.query.filter_by(id=publisher_id).first()
	publisher_books = Book.query.filter_by(pub_id=publisher_id).all()
	return render_template("publisher.html",publisher = publisher, publisher_books=publisher_books)

@main.route('/admin/menu/options/deletebook/<book_id>', methods=['GET','POST'])
@login_required
def delete_book(book_id):
	book = Book.query.get(book_id)
	if request.method == 'POST':
		db.session.delete(book)
		db.session.commit()
		flash('book deleted successfully')
		return redirect(url_for('main.book_details'))
	return render_template('delete.html',book=book)

@main.route('/admin/menu/options/', methods=['GET','POST'])
@login_required
def delete_book_selected():
	books = Book.query.all()
	return render_template('delete_books.html',books=books)

@main.route('/admin/menu/options/editbook/<book_id>',methods=['GET','POST'])
@login_required
def edit_book(book_id):
	form = EditForm()
	book = Book.query.get(book_id)
	form.title.data = book.title
	form.format.data = book.format
	form.num_pages.data = book.num_pages
	if form.validate_on_submit():
		form = EditForm()
		book = Book.query.get(book_id)
		book.title = form.title.data
		book.format = form.format.data
		book.num_pages = form.num_pages.data
		db.session.add(book)
		db.session.commit()
		flash('Book details has been successfully updated')
		return redirect(url_for('main.book_details'))
	return render_template('edit.html',form = form)

@main.route('/admin/menu',methods=['GET','POST'])
def book_modify():
	return render_template('menu.html')

@main.route('/admin/menu/addbook',methods=['GET','POST'])
def add_new_book():
	form = BookForm()

	if form.validate_on_submit():
		book = Book(form.title.data,form.author.data,form.avg_rating.data,form.format.data,form.image.data,form.num_pages.data,form.publication.data)
		db.session.add(book)
		db.session.commit()
		flash('Book added successfully')
		return redirect(url_for('main.book_details'))

	return render_template('add_book.html',form = form)

app/catalog/templates/add_book.html
{% extends 'layout.html' %}

{% block content %}
	<div class="container form">
		<h4>Add new book to catalog</h4>
		<hr><br>

		{{form.hidden_tag()}}
		
		{{ wtf.quick_form(form) }}
	</div>
{% endblock %}

app/catalog/templates/delete.html
{% extends "layout.html" %}

{% block content %}
 <div class="container" style="margin-left:45px">
 	<h4> Are you sure want to delete?</h4>
 	<hr><br>
 	<p>Book Title: {{book.title}}</p>
 	<p>Book Author: {{book.author}}</p>
 	<br>
 	<form action="{{url_for('main.delete_book',book_id = book.id)}}" method="POST">
 	<button type="submit" class="btn btn-primary">delete</button>
    </form>
 </div>
 {% endblock  %}

app/catalog/templates/delete_books.html
{% extends 'layout.html' %}

{% block content %}
<h4 style="margin-left: 50px">select the book to delete</h4>
<hr>
	<table style="margin-left:50px;margin-top:20px;border-collapse:separate;border-spacing:0 15px">
		<div class="container">
		{% for book in books %}
		<tr style="margin-bottom: 20px">
		<td><span style="font-family: Sansita;width:200px">{{book.title}}</span>&nbsp;&nbsp;</td>

		<td><a href="{{url_for('main.delete_book',book_id = book.id)}}"><button type="button" class="btn btn-primary">Delete</button></a>&nbsp;&nbsp;</td>

		<td><a href="{{url_for('main.edit_book',book_id = book.id)}}"><button type="button" class="btn btn-primary">Edit</button></a>&nbsp;&nbsp;</td>
		</tr>
		{% endfor %}
	    </div>
	</table>
{% endblock %}

app/catalog/templates/edit.html
{% extends 'layout.html' %}

{% block content %}
<div class="container form" style="margin-left: 45px">
	<h4> Do you want to edit book details?</h4><hr><br>

	{{form.hidden_tag()}}

	{{wtf.quick_form(form)}}

</div>
{% endblock %}

app/catalog/templates/home.html
{% extends 'layout.html' %}


{% block content %}
    <div class="container books">
        <div class="row">
        {% for book in books %}
            <div class="col-md-4">
                <img src="static/img/{{ book.image }}" alt="book-img" height="200" width="190" class="img-rounded">
                <h4> Title: {{ book.title }} </h4>
                <p> Authors: {{ book.author }} </p>
                <p> Format: {{ book.format }} </p>
                <p> Average Rating: {{ book.avg_rating }} </p>
                <p> Pages: {{ book.num_pages }} </p>
                <p>Publisher Name: <a href="{{ url_for('main.display_publisher', publisher_id=book.pub_id) }}"> {{ book.pub_name }}
                </a></p>
                <!--
                <span class="label label-primary"><a href="{{ url_for('main.delete_book',book_id=book.id) }}" style="color:floralwhite">Delete</a></span>
                <span class="label label-success"><a href="{{ url_for('main.edit_book',book_id=book.id) }}" style="color:floralwhite">Edit</a></span> -->
                <br><br><br>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock content %}

app/catalog/templates/layout.html
{% import  "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">

    {# head #}
    {% block head %}
        <head>
            <title> books Inc </title>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
            <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
            <script type="text/javascript" src="{{url_for('static',filename='js/dropdown.js')}}"></script>
        </head>
    {% endblock head %}

    {# body #}
    {% block body %}
    <body>
    <div class="wrapper">
        {# navigation bar #}
        {% block navbar %}
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar-brand title" href="{{ url_for('main.book_details') }}">Book Shop Around the Corner</a>

                <ul class="nav navbar-nav pull-right nav-list">
                    <li><a href="{{ url_for('main.book_details') }}"> Home </a></li>
                    <li><a href="{{ url_for('authentication.register_user') }}"> Register </a></li>
                    <li>
                        {% if current_user.is_authenticated %}
                            <a href="{{url_for('authentication.do_the_logout')}}">Logout</a>
                        {% else %}
                            <a href="{{url_for('authentication.do_the_login')}}">Signin</a>
                        {% endif %}
                    </li>
                    <li>
                        <a href="">
                            {% if current_user.is_authenticated %}
                                Loggged In as <b style="color:red">{{current_user.user_name.title()}}</b>
                            {% else %}
                                Not Logged In
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        {% if current_user.is_authenticated %}
                            {% if current_user.user_name.title() == 'Admin' %}
                                <a href="{{url_for('main.book_modify')}}">Menu</a>
                            {% endif %}
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
        {% endblock navbar %}

        {# flash messaging #}
        {% for message in get_flashed_messages() %}
        <div class="container alert alert-info alert-dismissible fade in">
        <a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{message}}
        </div>
        {% endfor %}

        {# empty block for custom content #}
        {% block content %} {% endblock content %}

        {# footer #}
        {% block footer %}
        <footer>
            <div class="container ftr">
                <hr>
                <p class="text-center small"> The Shop Around The Corner &copy;	| 2019 </p>
            </div>
        </footer>
        {% endblock footer %}

    </div>
    </body>
    {% endblock body %}
</html>

app/catalog/templates/menu.html
{% extends 'layout.html' %}

{% block content %}
	<div class="container form">
		<h4>Choose the option</h4>
		<hr><br>

		<a href="{{url_for('main.add_new_book')}}"><button type="button" class="btn btn-primary">Add new book</button></a>
		<a href="{{url_for('main.delete_book_selected')}}"><button type="button" class="btn btn-primary">Delete or modify existing books</button></a>
	</div>
{% endblock %}

app/catalog/templates/publisher.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container publisher">
        <h4> Books by {{ publisher.name }} </h4>
        <hr><br>
        <ol>
            {% for book in publisher_books %}
                <li>
                    {{ book.title }} by {{ book.author }}
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock content %}